# RabbitMQ properties
version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: golang_studies_rabbitmq_management

    ports:
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API
      - 5672:5672 # communication with the AMQP 0-9-1 and 1.0 clients

    volumes:
      # data persistence
      - /tmp/rabbitmq/data/:/var/lib/rabbitmq/
      # data mapping -> host: container
      # queues and messages data of the container will be stored on the host
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    restart: always

volumes:
  logs-folder:
    driver: local
